import React from 'react';
import {makeStyles} from '@material-ui/core/styles';
import Head from 'next/head';
import Image from 'next/image';
import {Swiper, SwiperSlide} from 'swiper/react';
import {Box, useMediaQuery, Grid, useTheme, Container, Typography} from '@material-ui/core';

import {Header, Footer, ContentBlock, Button, CategoryBlock, CartItem} from '~/components';
import {ProductWidget} from '~/components/Widgets';

const useStyles = makeStyles((theme) => ({
  bgBanner: {
    backgroundImage: 'url(/img/noise.png)',
    backgroundColor: '#FAF6EF',
  },
  title: {
    margin: '2rem 0 3rem',
    '& h2': {
      fontSize: '2rem',
      lineHeight: '3rem',
      fontWeight: 'bold',
    },
    '& .notice': {
      marginTop: '1rem',
      fontSize: '1rem',
      lineHeight: '1.563rem',
    },
    [theme.breakpoints.down('sm')]: {
      marginBottom: '1.75rem',
      '& h2': {
        fontSize: '1.25rem',
        lineHeight: '1.875rem',
      },
      '& .notice': {
        fontSize: '0.813rem',
      },
    },
  },
  store: {
    paddingBottom: '2rem',
  },
  continueShop: {
    paddingTop: '2rem',
  },
  banner: {
    padding: '2rem 0 1rem',
  },
  banner1: {
    padding: '1rem 0 4rem',
  },
}));

const recommendProducts = [
  {
    id: 8,
    name: '『大好評』江戸和竿についてご紹介しています。',
    price: 89.62,
    thumb_url: null,
    is_favorite_product: false,
    seller_info: {
      id: 3,
      name: '中台泰夫',
      catch_phrase: '木地部門　伝統工芸士',
      avatar_url: '/img/sellers/seller-01.png',
    },
    tags: [
      {
        id: 2,
        name: '農薬節約栽培',
      },
    ],
  },
  {
    id: 9,
    name: '『大好評』江戸和竿についてご紹介しています。',
    price: 89.62,
    thumb_url: null,
    is_favorite_product: false,
    seller_info: {
      id: 3,
      name: '中台泰夫',
      catch_phrase: '木地部門　伝統工芸士',
      avatar_url: '/img/sellers/seller-01.png',
    },
    tags: [
      {
        id: 2,
        name: '農薬節約栽培',
      },
    ],
  },
  {
    id: 10,
    name: '『大好評』江戸和竿についてご紹介しています。',
    price: 89.62,
    thumb_url: null,
    is_favorite_product: false,
    seller_info: {
      id: 3,
      name: '中台泰夫',
      catch_phrase: '木地部門　伝統工芸士',
      avatar_url: '/img/sellers/seller-01.png',
    },
    tags: [
      {
        id: 2,
        name: '農薬節約栽培',
      },
    ],
  },
  {
    id: 11,
    name: '『大好評』江戸和竿についてご紹介しています。',
    price: 89.62,
    thumb_url: null,
    is_favorite_product: false,
    seller_info: {
      id: 3,
      name: '中台泰夫',
      catch_phrase: '木地部門　伝統工芸士',
      avatar_url: '/img/sellers/seller-01.png',
    },
    tags: [
      {
        id: 2,
        name: '農薬節約栽培',
      },
    ],
  },
];

export default function Cart() {
  const classes = useStyles();
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('xs'));
  const isTablet = useMediaQuery(theme.breakpoints.down('md'));

  const renderProduct = () => {
    if (isMobile) {
      return (
        <Swiper
          slidesPerView={'auto'}
          spaceBetween={24}
          pagination={{
            clickable: true,
          }}
          className='productSwiper'
        >
          {recommendProducts.map((product, index) => (
            <SwiperSlide
              style={{width: '70%'}}
              key={String(index)}
            >
              <ProductWidget
                data={product}
                heart={true}
              />
            </SwiperSlide>
          ))}
        </Swiper>
      );
    } else if (isTablet) {
      return (
        <Swiper
          slidesPerView={2.5}
          spaceBetween={24}
          pagination={{
            clickable: true,
          }}
          className='productSwiper'
        >
          {recommendProducts.map((product, index) => (
            <SwiperSlide
              style={{width: '90%'}}
              key={String(index)}
            >
              <ProductWidget
                data={product}
                heart={true}
              />
            </SwiperSlide>
          ))}
        </Swiper>
      );
    }
    return (
      <Grid
        container={true}
        justifyContent='center'
        spacing={3}
      >
        {recommendProducts.map((product, index) => (
          <Grid
            key={String(index)}
            item={true}
            xs={12}
            sm={4}
            md={3}
          >
            <ProductWidget
              data={product}
              heart={true}
            />
          </Grid>
        ))}
      </Grid>
    );
  };

  /* eslint-disable max-lines */
  return (
    <>
      <Head>
        <title>{'Cart - BH_EC'}</title>
        <meta
          name='cart'
          content='Generated by NextJs'
        />
      </Head>
      <Header showMainMenu={false}/>

      {/* Cart */}
      <ContentBlock
        bgImage='/img/noise.png'
        bgRepeat='repeat'
        mixBlendMode='multiply'
      >
        <Grid
          container={true}
          spacing={0}
        >
          <Grid
            item={true}
            xs={12}
            md={12}
            lg={12}
          >
            <Box
              textAlign={'center'}
              className={classes.title}
            >
              <Typography variant={'h2'}>{'カート内の商品 (3点)'}</Typography>
              <div className={'notice'}>{'注文画面にて送料を必ずご確認ください。'}</div>
            </Box>
            <Box
              textAlign={'left'}
              className={classes.store}
            >
              <Button
                variant='pill'
                customColor='yellow'
                customSize='medium'
                startIcon={
                  <Image
                    src={'/img/icons/store.svg'}
                    width={24}
                    height={26}
                    alt={'store'}
                  />}
              >
                {'稲作本店（FARM1739）'}
              </Button>
            </Box>
          </Grid>
        </Grid>

        <CartItem/>

        <Grid
          container={true}
          spacing={0}
        >
          <Grid
            item={true}
            xs={12}
            md={12}
            lg={12}
          >
            <Box
              textAlign={'center'}
              className={classes.continueShop}
            >
              <Button
                variant='pill'
                customColor='black'
                customSize='extraLarge'
              >
                {'購入画面へすすむ'}
              </Button>
            </Box>

          </Grid>
        </Grid>
      </ContentBlock>

      {/* Recommend Product */}
      <CategoryBlock
        title='あなたにオススメの商品'
        bgColor='#FAF6EF'
        bgImage='/img/noise.png'
        bgRepeat='repeat'
        mixBlendMode='multiply'
      >
        {renderProduct()}
      </CategoryBlock>

      {/* Banner */}
      <div className={classes.bgBanner}>
        <Container maxWidth='lg'>
          <Grid
            container={true}
            className={classes.banner}
          >
            <Grid
              item={true}
              xs={12}
              md={12}
            >
              <Image
                src={'/img/banner-favorite2.png'}
                alt='banner bottom'
                layout={'responsive'}
                width={'1140'}
                height={'192'}
              />
            </Grid>
          </Grid>
          <Grid
            container={true}
            className={classes.banner1}
          >
            <Grid
              item={true}
              xs={12}
              md={12}
            >
              <Image
                src={'/img/banner.png'}
                alt='banner bottom'
                layout={'responsive'}
                width={'1140'}
                height={'192'}
              />
            </Grid>
          </Grid>
        </Container>
      </div>

      <Footer/>
    </>
  );
}
