version: '3'

services:
  web:
    container_name: bhec-fe
    build: './'
    restart: always
    env_file: 
      - ./.env
    ports:
      - 3001:3000
      - 9229:9229
    volumes: 
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
