import {Grid, Typography, Button, Box, TextField, CircularProgress} from '@material-ui/core';
import {makeStyles} from '@material-ui/core/styles';
import Head from 'next/head';
import {useForm, Controller} from 'react-hook-form';
import {ErrorMessage} from '@hookform/error-message';
import React, {useState} from 'react';

import {Footer} from '../../../components/Layout/Footer';
import {Header} from '../../../components/Layout/Header';
import {ContentBlock} from '../../../components/ContentBlock';
import {StyledForm} from '../../../components/StyledForm';

const useStyles = makeStyles((theme) => ({
  block: {
    width: '100%',
    display: 'flex',
    padding: '1.25rem 0',
    borderBottom: `1px solid ${theme.border.default}`,
    fontSize: '1.125rem',
    lineHeight: '2.188rem',
    color: 'black',
    '& h4': {
      margin: '0rem',
    },
  },

  title: {
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: '1.25rem',
    lineHeight: '2.5rem',
  },

  textDisable: {
    color: theme.textDisable.default,
  },
  btnSubmit: {
    background: theme.palette.buttonLogin.default,
    boxShadow: '0px 4px 8px rgba(0, 0, 0, 0.15)',
    borderRadius: '45px',
    color: theme.palette.background.default,
    padding: '0.5rem 2rem',
    '&:hover': {
      background: theme.palette.buttonLogin.default,
      color: theme.palette.background.default,
    },
  },
}));

const info = {
  username: 'はなこ',
  email: 'bh@gmail.com',
  password: '＊＊＊＊＊＊＊＊',
  fullName: '',
  alphabet: '',
  gender: '',
  birthday: '',
  address: '',
};

export default function BasicInfomationUpdate() {
  const classes = useStyles();
  const {control, handleSubmit, formState: {errors}} = useForm({criteriaMode: 'all'});
  const [loading, setLoading] = useState(false);

  const onSubmit = async () => {
    setLoading(true);
  };

  return (
    <div className={'page'}>
      <Head>
        <title>{'Order Detail - BH_EC'}</title>

        <meta
          name='description'
          content='Generated by NextJs'
        />
      </Head>

      <Header showMainMenu={false}/>

      <div className='content'>
        <ContentBlock
          title={'基本情報'}
        >
          <Grid
            container={true}
            spacing={3}
          >
            <StyledForm
              onSubmit={handleSubmit(onSubmit)}
              style={{width: '100%'}}
            >
              <div className={classes.block}>
                <Grid
                  item={true}
                  xs={12}
                  sm={4}
                  md={4}
                >
                  <Typography
                    variant={'h4'}
                    className={classes.title}
                  >{'注文ニックネーム番号'}</Typography>
                </Grid>
                <Grid
                  item={true}
                  xs={12}
                  sm={8}
                  md={8}
                >
                  <Controller
                    name='other_name'
                    control={control}
                    defaultValue=''
                    render={({field}) => (
                      <TextField
                        id='other_name'
                        label='⽒⽒名を入力してください'
                        variant='outlined'
                        InputLabelProps={{shrink: false}}
                        {...field}
                      />
                    )}
                  />
                  <ErrorMessage
                    errors={errors}
                    name='other_phone'
                    render={({messages}) => {
                      return messages ? Object.entries(messages).map(([type, message]) => (
                        <p
                          className='inputErrorText'
                          key={type}
                        >{`⚠ ${message}`}</p>
                      )) : null;
                    }}
                  />
                </Grid>
              </div>

              <div className={classes.block}>
                <Grid
                  item={true}
                  xs={12}
                  sm={4}
                  md={4}
                >
                  <Typography
                    variant={'h4'}
                    className={classes.title}
                  >{'ログインID'}</Typography>
                </Grid>
                <Grid
                  item={true}
                  xs={12}
                  sm={8}
                  md={8}
                >
                  {info.email}
                </Grid>
              </div>

              <div className={classes.block}>
                <Grid
                  item={true}
                  xs={12}
                  sm={4}
                  md={4}
                >
                  <Typography
                    variant={'h4'}
                    className={classes.title}
                  >{'パスワード'}</Typography>
                </Grid>
                <Grid
                  item={true}
                  xs={12}
                  sm={8}
                  md={8}
                >
                  {info.password}
                </Grid>
              </div>

              <div className={classes.block}>
                <Grid
                  item={true}
                  xs={12}
                  sm={4}
                  md={4}
                >
                  <Typography
                    variant={'h4'}
                    className={classes.title}
                  >{'氏名'}</Typography>
                </Grid>
                <Grid
                  item={true}
                  xs={12}
                  sm={8}
                  md={8}
                >
                  { info.fullName ? <span>{info.fullName}</span> : <span className={classes.textDisable}>{'未登録'}</span>}
                </Grid>
              </div>

              <div className={classes.block}>
                <Grid
                  item={true}
                  xs={12}
                  sm={4}
                  md={4}
                >
                  <Typography
                    variant={'h4'}
                    className={classes.title}
                  >{'ひらがな'}</Typography>
                </Grid>
                <Grid
                  item={true}
                  xs={12}
                  sm={8}
                  md={8}
                >
                  { info.alphabet ? <span>{info.alphabet}</span> : <span className={classes.textDisable}>{'未登録'}</span>}
                </Grid>
              </div>

              <div className={classes.block}>
                <Grid
                  item={true}
                  xs={12}
                  sm={4}
                  md={4}
                >
                  <Typography
                    variant={'h4'}
                    className={classes.title}
                  >{'性別'}</Typography>
                </Grid>

                <Grid
                  item={true}
                  xs={12}
                  sm={8}
                  md={8}
                >
                  { info.gender ? <span>{info.gender}</span> : <span className={classes.textDisable}>{'未登録'}</span>}
                </Grid>
              </div>
              <div className={classes.block}>
                <Grid
                  item={true}
                  xs={12}
                  sm={4}
                  md={4}
                >
                  <Typography
                    variant={'h4'}
                    className={classes.title}
                  >{'生年月日'}</Typography>
                </Grid>

                <Grid
                  item={true}
                  xs={12}
                  sm={8}
                  md={8}
                >
                  { info.birthday ? <span>{info.birthday}</span> : <span className={classes.textDisable}>{'未登録'}</span>}
                </Grid>
              </div>
              <div className={classes.block}>
                <Grid
                  item={true}
                  xs={12}
                  sm={4}
                  md={4}
                >
                  <Typography
                    variant={'h4'}
                    className={classes.title}
                  >{'住所'}</Typography>
                </Grid>

                <Grid
                  item={true}
                  xs={12}
                  sm={8}
                  md={8}
                >
                  { info.address ? <span>{info.address}</span> : <span className={classes.textDisable}>{'未登録'}</span>}
                </Grid>
              </div>
            </StyledForm>
          </Grid>
          <Box
            textAlign='center'
            mt={5}
          >
            <Button
              variant='pill'
              customColor='red'
              customSize='extraLarge'
              type='submit'
              className={classes.btnSubmit}
            >
              {'基本情報を編集'}
              {loading ? (
                <CircularProgress
                  size={24}
                />
              ) : null}
            </Button>
          </Box>
        </ContentBlock>
      </div>

      <Footer/>
    </div >
  );
}
