import {makeStyles} from '@material-ui/core/styles';

import Head from 'next/head';

import {Header} from '../../components/Layout/Header';
import {Footer} from '../../components/Layout/Footer';
import {TopBannerWidget} from '../../components/Widgets/TopBannerWidget';

const useStyles = makeStyles(() => ({
  root: {
    position: 'relative',
  },
}));

export default function SellerForm() {
  const classes = useStyles();
  return (
    <div className={classes.root}>
      <Head>
        <title>{'Seller Form - Oshinagaki Store'}</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
      </Head>

      <Header showMainMenu={false}/>

      <div className='content'>

        <TopBannerWidget
          variant='titleBanner'
          title='出品者登録'
          imgSrc='/img/heading-banner.png'
          imgWidth={1366}
          imgHeight={240}
          imgAlt='Seller Form'
        />

      </div>

      <Footer/>
    </div>
  );
}
