import {Grid} from '@material-ui/core';
import {makeStyles} from '@material-ui/core/styles';
import Head from 'next/head';

import {Footer} from '../../../components/Layout/Footer';
import {Header} from '../../../components/Layout/Header';
import {Block} from '../../../components/MyPage/Block';
import {OrderItem} from '../../../components/Order';

const useStyles = makeStyles((theme) => ({
  row: {
    width: '100%',
    display: 'flex',
    padding: '1.25rem 0',
    borderBottom: '1px solid rgba(33, 33, 33, 0.08)',
    fontSize: '1.125rem',
    lineHeight: '2.188rem',
    color: theme.palette.black.default,
    '& h4': {
      margin: '0rem',
    },
  },
  export: {
    width: '10.125rem',
    height: '2.875rem',
    border: 'none',
    background: theme.palette.grey.main,
    fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
    fontSize: '1.125rem',
    cursor: 'pointer',
  },
  contentBlock: {
    paddingBottom: '0',
  },
}));

const currency = new Intl.NumberFormat('ja-JP', {style: 'currency', currency: 'JPY'});

const order = {
  id: 1234567890,
  orderDate: '2021/01/01 01:30',
  username: '鈴木はなこ',
  postCode: '〒150-0043',
  address: '東京都渋谷区道玄坂2-29-1',
  addressNo: '渋谷マンション101号',
  phone: '090-0000-0000',
  paymentMethod: 'クレジットカード',
  shippingMethod: 'クール便',
  productSubtotal: 3000,
  shippingFee: 300,
  totalAmount: 3300,
  discount: 200,
  exported: true,
  orderDetails: [
    {
      productId: 1,
      name: '『大好評』小田原漆器についてご紹介しています。',
      image: '/img/products/product-01.png',
      url: '#',
      tags: [{name: '送料無料', isFeatured: true}, {name: '期間限定'}],
      price: 26600,
      owner: {
        id: 3214,
        name: '小田原漆器',
        avatar: '/img/sellers/seller-01.png',
        introduction: '木地部門　伝統工芸士',
      },
      quantity: 20,
      trackingNum: '01234567980',
      transportType: 'ヤマト運輸',
      status: 1,
    },
    {
      productId: 2,
      name: '『大好評』小田原漆器についてご紹介しています。',
      image: '/img/products/product-02.png',
      url: '#',
      tags: [{name: '送料無料', isFeatured: true}, {name: '農薬節約栽培'}, {name: '期間限定'}],
      price: 26600,
      owner: {
        id: 3217,
        name: '小田原漆器',
        avatar: '/img/sellers/seller-02.png',
        introduction: '木地部門　伝統工芸士',
      },
      quantity: 20,
      trackingNum: '01234567980',
      transportType: 'ヤマト運輸',
      status: 2,
    },
  ],
};

const OrdersDetail = () => {
  const classes = useStyles();
  const {id, orderDate, username, postCode, address, addressNo, phone, paymentMethod, shippingMethod, productSubtotal, shippingFee, totalAmount, discount, exported, orderDetails} = order;
  return (
    <div className={'page'}>
      <Head>
        <title>{'Order Detail - BH_EC'}</title>

        <meta
          name='description'
          content='Generated by NextJs'
        />
      </Head>

      <Header showMainMenu={false}/>

      <div className='content'>
        <Block
          title={'注文詳細'}
          paddingBot={'1.438rem'}
        >
          <Grid
            container={true}
            spacing={0}
          >
            <div className={classes.row}>
              <Grid
                item={true}
                md={3}
              >
                <h4>{'注文番号'}</h4>
              </Grid>
              <Grid
                item={true}
                md={9}
              >
                {id}
              </Grid>
            </div>

            <div className={classes.row}>
              <Grid
                item={true}
                md={3}
              >
                <h4>{'注文日時'}</h4>
              </Grid>
              <Grid
                item={true}
                md={9}
              >
                {orderDate}
              </Grid>
            </div>

            <div className={classes.row}>
              <Grid
                item={true}
                md={3}
              >
                <h4>{'お届け先住所'}</h4>
              </Grid>
              <Grid
                item={true}
                md={9}
              >
                {username}<br/>
                {postCode}<br/>
                {address}<br/>
                {addressNo}<br/>
                {phone}
              </Grid>
            </div>

            <div className={classes.row}>
              <Grid
                item={true}
                md={3}
              >
                <h4>{'決済方法'}</h4>
              </Grid>
              <Grid
                item={true}
                md={9}
              >
                {paymentMethod}
              </Grid>
            </div>

            <div className={classes.row}>
              <Grid
                item={true}
                md={3}
              >
                <h4>{'配送方法'}</h4>
              </Grid>
              <Grid
                item={true}
                md={9}
              >
                {shippingMethod}
              </Grid>
            </div>

            <div className={classes.row}>
              <Grid
                item={true}
                md={3}
              >
                <h4>{'購入明細書'}</h4>
                <div>{'商品の小計'}</div>
                <div>{'配送料'}</div>
                <div>{'注文合計'}</div>
                <div>{'クーポン利用'}</div>
                <h4>{'ご請求金額'}</h4>
              </Grid>

              <Grid
                item={true}
                md={7}
              >
                <br/>
                {currency.format(productSubtotal)}<br/>
                {currency.format(shippingFee)}<br/>
                {currency.format(totalAmount)}<br/>
                {'- ' + currency.format(discount)}<br/>
                <h4>
                  {currency.format(
                    productSubtotal + shippingFee +
                    (totalAmount - discount),
                  )}
                </h4>
              </Grid>

              <Grid
                item={true}
                md={2}
              >
                <button className={classes.export}>{exported ? '再発行' : '領収書発行'}</button>
              </Grid>
            </div>
          </Grid>
        </Block>

        {orderDetails.map((detail) => (
          <OrderItem
            key={`orderDetail-${detail.id}`}
            data={detail}
          />
        ))}
      </div>

      <Footer/>
    </div >
  );
};

export default OrdersDetail;
