/* eslint-disable max-lines */
/* eslint-disable no-useless-escape */
import 'date-fns';
import {makeStyles} from '@material-ui/core/styles';
import Head from 'next/head';

import React from 'react';

import {Header} from '../../../components/Layout/Header';
import {Footer} from '../../../components/Layout/Footer';
import {TopBannerWidget} from '../../../components/Widgets/TopBannerWidget';
import {ContentBlock} from '../../../components/ContentBlock';

const useStyles = makeStyles(() => ({
  root: {
    position: 'relative',
  },
}));

export default function Thanks() {
  const classes = useStyles();

  return (
    <div className={classes.root}>
      <Head>
        <title>{'Thank you to become a seller - Oshinagaki Store'}</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
      </Head>

      <Header showMainMenu={false}/>

      <div className='content'>

        <TopBannerWidget
          variant='titleBanner'
          title='出品者登録'
          imgSrc='/img/heading-banner.png'
          imgWidth={1366}
          imgHeight={240}
          imgAlt='Seller Form'
        />
        <ContentBlock
          title='Thank you !!!'
          bgImage='/img/noise.png'
          bgRepeat='repeat'
          mixBlendMode='multiply'
        />
      </div>

      <Footer/>
    </div>
  );
}
