import Head from 'next/head';
import Image from 'next/image';

import {Box, Container, Grid} from '@material-ui/core';

import {Header} from '../components/Layout/Header';
import {Footer} from '../components/Layout/Footer';
import {ContentBlock} from '../components/ContentBlock';
import {Feature} from '../components/Widgets/Feature';
import {StepWidget as ProductArrivalStep} from '../components/Widgets/StepWidget';

export default function About() {
  return (
    <div className={'page page-about'}>
      <Head>
        <title>{'About - BH_EC'}</title>
        <meta
          name='description'
          content='Generated by NextJs'
        />
      </Head>

      <Header showMainMenu={false}/>

      <div className='content'>
        <div id={'top-banner'}>
          <Image
            src={'/img/video-banner.png'}
            layout='responsive'
            width={1366}
            height={640}
            alt={'Video banner'}
          />
        </div>

        <ContentBlock
          title={'おしながきの特徴'}
          description={'生産者から直送！新鮮で厳選された商品をお届けするのは今や当たり前！\n' +
          'おしながきではこんな特徴があります'}
        >
          <Grid
            container={true}
            justify={'center'}
            spacing={3}
          >
            <Grid
              item={true}
              xs={12}
              sm={6}
              md={4}
            >
              <Feature
                title={'見つかる'}
              >
                {'自分だけの'} <br/>
                {'こだわり商品を簡単に'} <br/>
                {'見つけることができる！'}
              </Feature>
            </Grid>
            <Grid
              item={true}
              xs={12}
              sm={6}
              md={4}
            >
              <Feature
                title={'知る'}
                type={'know'}
              >
                {'生産者やつくられ方'} <br/>
                {'歴史や文化まで'} <br/>
                {'知ることができる！'}
              </Feature>
            </Grid>
            <Grid
              item={true}
              xs={12}
              sm={6}
              md={4}
            >
              <Feature
                title={'応援する'}
                type={'support'}
              >
                {'商品を購入することで'} <br/>
                {'ふるさとや好きな地域を'} <br/>
                {'応援することができる！'} <br/>
                <span
                  style={{
                    fontSize: '0.875rem',
                    lineHeight: '1.375rem',
                    color: '#444',
                    marginTop: '1rem',
                    display: 'inline-block',
                  }}
                >{'*利益の2%を地方へ還元'}</span>
              </Feature>
            </Grid>
          </Grid>
        </ContentBlock>

        <ContentBlock
          title={'充実のサポート体制'}
          bgColor={'#FAF6EF'}
          bgImage={'/img/noise.png'}
          bgRepeat={'repeat'}
          mixBlendMode={'multiply'}
        >
          <Container>
            <Grid
              container={true}
              justify={'center'}
              alignItems={'center'}
            >
              <Box py={4}>
                <Image
                  src={'/img/support-system-lifecycle.png'}
                  width={692}
                  height={692}
                  alt={'Support system lifecycle'}
                />
              </Box>
            </Grid>
          </Container>
        </ContentBlock>

        <ContentBlock title={'簡単３ステップで商品到着'}>
          <Grid
            container={true}
            justify={'center'}
            spacing={3}
          >
            <Grid
              item={true}
              xs={12}
              sm={6}
              md={4}
            >
              <ProductArrivalStep
                title={'Step1'}
              >
                <Box fontWeight={'bold'}>
                  {'スマホやPCから'} <br/>
                  {'商品を選択して簡単注文！'}
                </Box>
                <Box
                  textAlign={'center'}
                  mt={2}
                  mb={-4}
                >
                  <Image
                    width={217}
                    height={207}
                    alt={'簡単３ステップで商品到着 - STEP1'}
                    src={'/img/product-arrival-step-1.png'}
                  />
                </Box>
              </ProductArrivalStep>
            </Grid>

            <Grid
              item={true}
              xs={12}
              sm={6}
              md={4}
            >
              <ProductArrivalStep
                title={'Step2'}
              >
                <Box
                  lineHeight={'4rem'}
                  fontWeight={'bold'}
                >
                  {'発送を待つだけ'}
                </Box>
                <Box
                  textAlign={'center'}
                  mt={2}
                  mb={-4}
                >
                  <Image
                    width={217}
                    height={207}
                    alt={'簡単３ステップで商品到着 - STEP2'}
                    src={'/img/product-arrival-step-2.png'}
                  />
                </Box>
              </ProductArrivalStep>
            </Grid>

            <Grid
              item={true}
              xs={12}
              sm={6}
              md={4}
            >
              <ProductArrivalStep
                title={'Step3'}
              >
                <Box
                  lineHeight={'4rem'}
                  fontWeight={'bold'}
                >
                  {'お家で受け取り'}
                </Box>
                <Box
                  textAlign={'center'}
                  mt={2}
                  mb={-4}
                >
                  <Image
                    width={217}
                    height={207}
                    alt={'簡単３ステップで商品到着 - STEP3'}
                    src={'/img/product-arrival-step-3.png'}
                  />
                </Box>
              </ProductArrivalStep>
            </Grid>
          </Grid>
        </ContentBlock>

      </div>

      <Footer/>
    </div>
  );
}
