import Head from 'next/head';
import Image from 'next/image';

import {Grid} from '@material-ui/core';

import {Header} from '../components/Layout/Header';
import {Footer} from '../components/Layout/Footer';
import {ContentBlock} from '../components/ContentBlock';
import {Feature} from '../components/Widgets/Feature';

export default function About() {
  return (
    <div className={'page page-about'}>
      <Head>
        <title>{'About - BH_EC'}</title>
        <meta
          name='description'
          content='Generated by NextJs'
        />
      </Head>

      <Header showMainMenu={false}/>

      <div className='content'>
        <div id={'top-banner'}>
          <Image
            src={'/img/video-banner.png'}
            layout='responsive'
            width={1366}
            height={640}
            alt={'Video banner'}
          />
        </div>

        <ContentBlock
          title={'おしながきの特徴'}
          description={'生産者から直送！新鮮で厳選された商品をお届けするのは今や当たり前！\n' +
          'おしながきではこんな特徴があります'}
        >
          <Grid
            container={true}
            justify={'center'}
            spacing={3}
          >
            <Grid
              item={true}
              xs={12}
              sm={6}
              md={4}
            >
              <Feature
                title={'見つかる'}
              >
                {'自分だけの'} <br/>
                {'こだわり商品を簡単に'} <br/>
                {'見つけることができる！'}
              </Feature>
            </Grid>
            <Grid
              item={true}
              xs={12}
              sm={6}
              md={4}
            >
              <Feature
                title={'知る'}
                type={'know'}
              >
                {'生産者やつくられ方'} <br/>
                {'歴史や文化まで'} <br/>
                {'知ることができる！'}
              </Feature>
            </Grid>
            <Grid
              item={true}
              xs={12}
              sm={6}
              md={4}
            >
              <Feature
                title={'応援する'}
                type={'support'}
              >
                {'商品を購入することで'} <br/>
                {'ふるさとや好きな地域を'} <br/>
                {'応援することができる！'} <br/>
                <span
                  style={{
                    fontSize: '0.875rem',
                    lineHeight: '1.375rem',
                    color: '#444',
                    marginTop: '1rem',
                    display: 'inline-block',
                  }}
                >{'*利益の2%を地方へ還元'}</span>
              </Feature>
            </Grid>
          </Grid>
        </ContentBlock>
      </div>

      <Footer/>
    </div>
  );
}
