import Head from 'next/head';

import {Container} from '@material-ui/core';

import {Header} from '../components/Layout/Header';
import {Footer} from '../components/Layout/Footer';

export default function About() {
  return (
    <div className={'page page-about'}>
      <Head>
        <title>{'About - BH_EC'}</title>
        <meta
          name='description'
          content='Generated by NextJs'
        />
      </Head>

      <Header/>

      <Container>
        <div style={{padding: '15px 0'}}>
          {[...new Array(85)].
            map(
              () => `Cras mattis consectetur purus sit amet fermentum.
                      Cras justo odio, dapibus ac facilisis in, egestas eget quam.
                      Morbi leo risus, porta ac consectetur ac, vestibulum at eros.
                      Praesent commodo cursus magna, vel scelerisque nisl consectetur et.`,
            ).
            join('\n')}
        </div>
      </Container>

      <Footer/>
    </div>
  );
}
