import Head from 'next/head';
import {makeStyles} from '@material-ui/core/styles';
import {Grid} from '@material-ui/core';

import {Header} from '../components/Layout/Header';
import {Breadcrumbs} from '../components/Breadcrumbs';
import {Block} from '../components/MyPage/Block';
import {UserAccount} from '../components/MyPage/UserAccount';
import {Notifications} from '../components/MyPage/Notifications';

import {BoxLink} from '../components/MyPage/BoxLink';
import {ButtonLink} from '../components/MyPage/ButtonLink';
import {ProductWidget} from '../components/Widgets/ProductWidget';
import {Footer} from '../components/Layout/Footer';

const useStyles = makeStyles(() => ({
  userInfo: {
    padding: '2.75rem 0 3.625rem',
    display: 'flex',
    justifyContent: 'space-between',
  },
  boxLink: {
    '& .MuiGrid-item': {
      paddingTop: '0',
      paddingBottom: '0',
    },
  },
  recommendedProducts: {
    marginTop: '2rem',
  },
}));

const notifications = [
  {
    id: 1,
    avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMo03l8HKKj-8SUhLfwJ9qGXw4TvyKWNcLlA&usqp=CAU',
    content: '通知１通知１通知１通知１通知１通知１通知１通知１通知１通知１通知１通知１通知１通知１通知１通知１通知１通知１通知１',
  },
  {
    id: 2,
    avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMo03l8HKKj-8SUhLfwJ9qGXw4TvyKWNcLlA&usqp=CAU',
    content: '通知2テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト',
  },
  {
    id: 3,
    avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMo03l8HKKj-8SUhLfwJ9qGXw4TvyKWNcLlA&usqp=CAU',
    content: '通知3テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト',
  },
  {
    id: 4,
    avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMo03l8HKKj-8SUhLfwJ9qGXw4TvyKWNcLlA&usqp=CAU',
    content: '通知4テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト',
  },
  {
    id: 5,
    avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMo03l8HKKj-8SUhLfwJ9qGXw4TvyKWNcLlA&usqp=CAU',
    content: '通知5テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト',
  },
];

const buttonLinks = [
  '基本情報',
  'お届け先情報',
  '決済方法',
  '割引クーポン',
  'お問い合わせ一覧',
  'フォロー中の出品者一覧',
  '返品/交換申請',
  '返品/交換一覧',
  'ログアウト',
];

const linkProps = [
  {
    id: 1,
    linkLabel: 'パンクズ',
    linkUrl: '/',
  },
  {
    id: 2,
    linkLabel: 'パンクズ',
    linkUrl: '/',
  },
  {
    id: 3,
    linkLabel: 'パンクズ',
  },
];

const boxLinks = [
  {
    image: '/img/icons/list.svg',
    content: '注文確認',
    url: '/orders',
  },
  {
    image: '/img/icons/heart.svg',
    content: 'お気に入り商品',
    url: '/',
  },
];

const recommendProducts = [
  {
    productId: 1,
    productName: '『大好評』東京アンチモニー工芸品についてご紹介しています。',
    productThumb: '/img/products/product-01.png',
    productUrl: '#',
    productTags: [{name: '送料無料', isFeatured: true}, {name: '期間限定'}],
    productPrice: 26600,
    favoriteProduct: true,
    productOwner: {
      name: '小田原漆器',
      avatar: '/img/sellers/seller-01.png',
      introduction: '木地部門　伝統工芸士',
    },
  },
  {
    productId: 2,
    productName: '『大好評』東京アンチモニー工芸品についてご紹介しています。',
    productThumb: '/img/products/product-02.png',
    productUrl: '#',
    productTags: [{name: '送料無料', isFeatured: true}, {name: '農薬節約栽培'}, {name: '期間限定'}],
    productPrice: 32800,
    favoriteProduct: true,
    productOwner: {
      name: '磯貝 剛',
      avatar: '/img/sellers/seller-02.png',
      introduction: 'ベッ甲イソガイ　統括',
    },
  },
  {
    productId: 3,
    productName: '『大好評』東京アンチモニー工芸品についてご紹介しています。',
    productThumb: '/img/products/product-03.png',
    productUrl: '#',
    productTags: [{name: '送料無料', isFeatured: true}, {name: '期間限定'}],
    productPrice: 149300,
    favoriteProduct: false,
    productOwner: {
      name: '林　文雄',
      avatar: '/img/sellers/seller-03.png',
      introduction: 'アートランド',
    },
  },
];

export default function MyPage() {
  const classes = useStyles();

  return (
    <div className={'page'}>
      <Head>
        <title>{'MyPage - BH_EC'}</title>

        <meta
          name='description'
          content='Generated by NextJs'
        />
      </Head>

      <Header showMainMenu={false}/>

      <div className='content'>
        <Breadcrumbs linkProps={linkProps}/>

        <Block title={'マイページ'}>
          <div className={classes.userInfo}>
            <UserAccount/>

            <Notifications notifications={notifications}/>
          </div>

          <Grid
            container={true}
            spacing={5}
            className={classes.boxLink}
          >
            {boxLinks.map((item) => (
              <Grid
                key={item.url}
                item={true}
                md={4}
              >
                <BoxLink link={item}/>
              </Grid>
            ))}
          </Grid>

          <Grid
            container={true}
            spacing={5}
            className={classes.buttomLink}
          >
            {buttonLinks.map((item) => (
              <Grid
                key={item}
                item={true}
                md={4}
              >
                <ButtonLink linkLabel={item}/>
              </Grid>
            ))}
          </Grid>
        </Block>

        <Block title={'あなたにオススメの商品'}>
          <Grid
            container={true}
            spacing={4}
            className={classes.recommendedProducts}
          >
            {recommendProducts.map((product) => (
              <Grid
                key={product.productId}
                item={true}
                md={4}
              >
                <ProductWidget
                  data={product}
                  heart={true}
                  border={'borderNone'}
                />
              </Grid>
            ))}
          </Grid>
        </Block>
      </div>

      <Footer/>
    </div>
  );
}
